# Generated by Django 4.0.6 on 2022-07-13 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_confirmpwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmpwd',
            field=models.CharField(default='', max_length=10),
        ),
    ]
