# Generated by Django 4.0.6 on 2022-07-18 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user_confirmpwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30)),
                ('status', models.CharField(default='pending', max_length=9)),
                ('priority', models.IntegerField(default=1, max_length=1)),
            ],
        ),
    ]
