# Generated by Django 4.0.6 on 2022-07-18 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_todos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todos',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
