# Generated by Django 4.0.6 on 2022-07-18 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_todos_priority'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todos',
            new_name='Todo',
        ),
    ]
